<a href="https://colab.research.google.com/github/mesha4545a/Assigment-2/blob/master/feature_extraction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
link = 'https://github.com/gumdropsteve/intro_to_machine_learning/raw/main/day_04/data/jeddah.csv'
df = pd.read_csv(link)

df.head()

                           ds  ... chefs_kitchen_bool
0  2021-01-20 04:13:49.541603  ...                NaN
1  2021-01-20 04:13:49.541603  ...                NaN
2  2021-01-20 04:13:49.541603  ...                NaN
3  2021-01-20 04:13:49.541603  ...                NaN
4  2021-01-20 04:13:49.541603  ...                NaN

[5 rows x 40 columns]

In [5]:
df.ds.unique()

array(['2021-01-20 04:13:49.541603', '2021-01-20 04:13:52.067842',
       '2021-01-20 04:13:55.093133', '2021-01-20 04:13:57.538588',
       '2021-01-20 04:14:00.051859', '2021-01-20 04:14:02.462407',
       '2021-01-20 04:14:04.905867', '2021-01-20 04:14:07.947726',
       '2021-01-20 04:14:11.425418', '2021-01-20 04:14:13.575662',
       '2021-01-20 04:14:17.271312', '2021-01-20 04:14:19.727735',
       '2021-01-20 04:14:21.740350', '2021-01-20 04:14:24.712395',
       '2021-01-20 04:14:26.898579', '2021-01-20 04:14:29.929431',
       '2021-01-20 04:14:32.959319', '2021-01-20 04:14:34.906108',
       '2021-01-20 04:14:37.483213', '2021-01-20 04:14:42.520726',
       '2021-01-20 04:14:45.359130', '2021-01-20 04:14:48.057906',
       '2021-01-20 04:14:50.783610', '2021-01-20 04:14:54.203455',
       '2021-01-20 04:14:57.075769', '2021-01-20 04:14:59.534188',
       '2021-01-20 04:15:01.771200', '2021-01-20 04:15:04.780146',
       '2021-01-20 04:15:07.909769', '2021-01-20 04:15:10.277434',
       '2021-01-20 04:15:13.417028', '2021-01-20 04:15:16.542662',
       '2021-01-20 04:15:19.088848', '2021-01-20 04:15:21.998062',
       '2021-01-20 04:15:25.006011', '2021-01-20 04:15:27.858378',
       '2021-01-20 04:15:30.172181', '2021-01-20 04:15:32.773252',
       '2021-01-20 04:15:37.692055', '2021-01-20 04:15:40.566359',
       '2021-01-20 04:15:42.563015', '2021-01-20 04:15:45.397428',
       '2021-01-20 04:15:51.614788', '2021-01-20 04:15:54.221352',
       '2021-01-20 04:15:57.933418', '2021-01-20 04:16:00.546423',
       '2021-01-21 04:37:42.123148', '2021-01-21 04:37:45.097999',
       '2021-01-21 04:37:48.239345', '2021-01-21 04:37:50.764706',
       '2021-01-21 04:37:54.378943', '2021-01-21 04:37:57.860355',
       '2021-01-21 04:37:59.788799', '2021-01-21 04:38:01.984399',
       '2021-01-21 04:38:03.529610', '2021-01-21 04:38:05.908594',
       '2021-01-21 04:38:08.587648', '2021-01-21 04:38:10.873327',
       '2021-01-21 04:38:13.048896', '2021-01-21 04:38:15.455800',
       '2021-01-21 04:38:18.155277', '2021-01-21 04:38:20.546444',
       '2021-01-21 04:38:22.971308', '2021-01-21 04:38:25.875049',
       '2021-01-21 04:38:27.312941', '2021-01-21 04:38:29.411159',
       '2021-01-21 04:38:32.276832', '2021-01-21 04:38:34.582014',
       '2021-01-21 04:38:37.085202', '2021-01-21 04:38:39.141124',
       '2021-01-21 04:38:41.602341', '2021-01-21 04:38:43.301177',
       '2021-01-21 04:38:45.368255', '2021-01-21 04:38:47.077721',
       '2021-01-21 04:38:48.773231', '2021-01-21 04:38:50.373337',
       '2021-01-21 04:38:52.892874', '2021-01-21 04:38:55.243525',
       '2021-01-21 04:38:57.266307', '2021-01-21 04:38:59.522704',
       '2021-01-21 04:39:01.906611', '2021-01-21 04:39:04.980016',
       '2021-01-21 04:39:07.338291', '2021-01-21 04:39:09.123381',
       '2021-01-21 04:39:12.789187', '2021-01-21 04:39:14.431101',
       '2021-01-21 04:39:16.835459', '2021-01-21 04:39:18.700094',
       '2021-01-21 04:39:22.547024', '2021-01-21 04:39:24.284012',
       '2021-01-21 04:39:26.553485', '2021-01-21 04:39:28.320354',
       '2021-01-22 15:45:53.344736', '2021-01-22 15:45:56.366630',
       '2021-01-22 15:45:59.070280', '2021-01-22 15:46:01.752860',
       '2021-01-22 15:46:04.033917', '2021-01-22 15:46:05.899133',
       '2021-01-22 15:46:08.655236', '2021-01-22 15:46:10.195323',
       '2021-01-22 15:46:12.023969', '2021-01-22 15:46:14.845495',
       '2021-01-22 15:46:17.899377', '2021-01-22 15:46:19.789351',
       '2021-01-22 15:46:21.772170', '2021-01-22 15:46:23.720251',
       '2021-01-22 15:46:26.057034', '2021-01-22 15:46:28.313164',
       '2021-01-22 15:46:31.005721', '2021-01-22 15:46:33.015954',
       '2021-01-22 15:46:34.968111', '2021-01-22 15:46:37.619131',
       '2021-01-22 15:46:39.532205', '2021-01-22 15:46:42.529680',
       '2021-01-22 15:46:45.212938', '2021-01-22 15:46:47.543897',
       '2021-01-22 15:46:49.175496', '2021-01-22 15:46:51.368662',
       '2021-01-22 15:46:53.719572', '2021-01-22 15:46:55.570035',
       '2021-01-22 15:46:58.745218', '2021-01-22 15:47:01.456081',
       '2021-01-22 15:47:03.200395', '2021-01-22 15:47:05.741593',
       '2021-01-22 15:47:08.785554', '2021-01-22 15:47:10.988763',
       '2021-01-22 15:47:13.118690', '2021-01-22 15:47:15.287863',
       '2021-01-22 15:47:17.534891', '2021-01-22 15:47:19.154248',
       '2021-01-22 15:47:22.630607', '2021-01-22 15:47:24.578188',
       '2021-01-22 15:47:26.396372', '2021-01-22 15:47:28.586893',
       '2021-01-22 15:47:31.551347', '2021-01-22 15:47:32.701643',
       '2021-01-22 15:47:35.505611', '2021-01-22 15:47:37.170865',
       '2021-01-23 17:17:03.964348', '2021-01-23 17:17:06.866375',
       '2021-01-23 17:17:08.833192', '2021-01-23 17:17:11.042280',
       '2021-01-23 17:17:13.191940', '2021-01-23 17:17:15.286424',
       '2021-01-23 17:17:17.140030', '2021-01-23 17:17:19.611897',
       '2021-01-23 17:17:21.541735', '2021-01-23 17:17:23.586376',
       '2021-01-23 17:17:25.038063', '2021-01-23 17:17:27.284562',
       '2021-01-23 17:17:29.596529', '2021-01-23 17:17:31.553402',
       '2021-01-23 17:17:33.531111', '2021-01-23 17:17:35.818003',
       '2021-01-23 17:17:37.867532', '2021-01-23 17:17:39.509351',
       '2021-01-23 17:17:41.514299', '2021-01-23 17:17:43.790817',
       '2021-01-23 17:17:46.141562', '2021-01-23 17:17:48.594424',
       '2021-01-23 17:17:51.831519', '2021-01-23 17:17:54.006047',
       '2021-01-23 17:17:56.582288', '2021-01-23 17:17:58.303647',
       '2021-01-23 17:18:00.031024', '2021-01-23 17:18:01.673539',
       '2021-01-23 17:18:03.744688', '2021-01-23 17:18:04.999331',
       '2021-01-23 17:18:06.802634', '2021-01-23 17:18:09.080538',
       '2021-01-23 17:18:11.318561', '2021-01-23 17:18:13.045979',
       '2021-01-23 17:18:14.711523', '2021-01-23 17:18:16.318388',
       '2021-01-23 17:18:19.221619', '2021-01-23 17:18:21.212292',
       '2021-01-23 17:18:24.633137', '2021-01-23 17:18:26.467276',
       '2021-01-23 17:18:28.437959', '2021-01-23 17:18:29.935948',
       '2021-01-23 17:18:33.396687', '2021-01-23 17:18:35.285633',
       '2021-01-23 17:18:37.202502', '2021-01-23 17:18:39.306873',
       '2021-01-25 04:52:00.090843', '2021-01-25 04:52:03.050098',
       '2021-01-25 04:52:05.712456', '2021-01-25 04:52:09.801479',
       '2021-01-25 04:52:14.754131', '2021-01-25 04:52:16.875778',
       '2021-01-25 04:52:20.138271', '2021-01-25 04:52:23.573836',
       '2021-01-25 04:52:25.827807', '2021-01-25 04:52:28.423885',
       '2021-01-25 04:52:31.286717', '2021-01-25 04:52:33.414939',
       '2021-01-25 04:52:36.084506', '2021-01-25 04:52:38.537130',
       '2021-01-25 04:52:41.464097', '2021-01-25 04:52:43.589047',
       '2021-01-25 04:52:45.955094', '2021-01-25 04:52:48.462525',
       '2021-01-25 04:52:51.072698', '2021-01-25 04:52:53.612543',
       '2021-01-25 04:52:56.270779', '2021-01-25 04:52:59.575999',
       '2021-01-25 04:53:01.796662', '2021-01-25 04:53:04.019639',
       '2021-01-25 04:53:06.249313', '2021-01-25 04:53:09.147866',
       '2021-01-25 04:53:12.148770', '2021-01-25 04:53:14.507499',
       '2021-01-25 04:53:16.735928', '2021-01-25 04:53:20.771751',
       '2021-01-25 04:53:22.811170', '2021-01-25 04:53:25.070688',
       '2021-01-25 04:53:27.089237', '2021-01-25 04:53:29.802216',
       '2021-01-25 04:53:32.131551', '2021-01-25 04:53:34.886433',
       '2021-01-25 04:53:36.761821', '2021-01-25 04:53:40.137964',
       '2021-01-25 04:53:45.210869', '2021-01-25 04:53:46.919816',
       '2021-01-25 04:53:50.212340', '2021-01-25 04:53:52.462128',
       '2021-01-25 04:53:57.277559', '2021-01-25 04:54:00.223606',
       '2021-01-25 04:54:03.433249', '2021-01-25 04:54:06.536306',
       '2021-01-26 05:18:00.673285', '2021-01-26 05:18:04.231778',
       '2021-01-26 05:18:07.315962', '2021-01-26 05:18:10.552353',
       '2021-01-26 05:18:13.639435', '2021-01-26 05:18:16.093637',
       '2021-01-26 05:18:18.092487', '2021-01-26 05:18:20.684785',
       '2021-01-26 05:18:23.815747', '2021-01-26 05:18:26.264535',
       '2021-01-26 05:18:28.654791', '2021-01-26 05:18:32.061960',
       '2021-01-26 05:18:35.533590', '2021-01-26 05:18:38.146339',
       '2021-01-26 05:18:40.931868', '2021-01-26 05:18:43.842320',
       '2021-01-26 05:18:47.972527', '2021-01-26 05:18:51.036152',
       '2021-01-26 05:18:54.539016', '2021-01-26 05:18:57.313782',
       '2021-01-26 05:19:00.351123', '2021-01-26 05:19:03.248832',
       '2021-01-26 05:19:06.630669', '2021-01-26 05:19:09.224912',
       '2021-01-26 05:19:11.619002', '2021-01-26 05:19:14.165384',
       '2021-01-26 05:19:16.903060', '2021-01-26 05:19:19.264047',
       '2021-01-26 05:19:22.218394', '2021-01-26 05:19:23.663807',
       '2021-01-26 05:19:26.306813', '2021-01-26 05:19:28.859077',
       '2021-01-26 05:19:31.419097', '2021-01-26 05:19:33.778122',
       '2021-01-26 05:19:37.149188', '2021-01-26 05:19:39.824402',
       '2021-01-26 05:19:42.625521', '2021-01-26 05:19:45.954653',
       '2021-01-26 05:19:50.465759', '2021-01-26 05:19:54.663536',
       '2021-01-26 05:19:57.609097', '2021-01-26 05:19:59.971956',
       '2021-01-26 05:20:05.315550', '2021-01-26 05:20:07.543757',
       '2021-01-26 05:20:10.419051', '2021-01-26 05:20:12.672633'],
      dtype=object)

In [6]:

df.ds.str.split(expand=True)[0]

0       2021-01-20
1       2021-01-20
2       2021-01-20
3       2021-01-20
4       2021-01-20
           ...
5515    2021-01-26
5516    2021-01-26
5517    2021-01-26
5518    2021-01-26
5519    2021-01-26
Name: 0, Length: 5520, dtype: object

In [8]:
df.ds.str.split(expand=True)[0].unique()

array(['2021-01-20', '2021-01-21', '2021-01-22', '2021-01-23',
       '2021-01-25', '2021-01-26'], dtype=object)

In [9]:
df['type']

0                     Entire loft
1                Entire apartment
2              Entire condominium
3                Entire apartment
4       Entire serviced apartment
                  ...
5515             Entire apartment
5516                 Private room
5517             Entire apartment
5518             Entire apartment
5519             Entire apartment
Name: type, Length: 5520, dtype: object

In [10]:
len(df['type'].unique())

21

In [11]:
df['type'].value_counts()

Entire apartment             3118
Private room                  663
Entire serviced apartment     355
Room                          209
Hotel room                    193
Entire villa                  192
Entire house                  181
Entire condominium            173
Entire loft                   146
Entire chalet                  72
Entire guest suite             51
Resort room                    38
Shared room                    28
Entire townhouse               24
Entire place                   15
Entire bungalow                14
Earth house                    12
Tiny house                     12
Entire cottage                 10
Farm stay                       7
Cycladic house                  7
Name: type, dtype: int64

In [14]:
d = [{'type':v} for v in df.type]
pd.DataFrame(d)

                           type
0                   Entire loft
1              Entire apartment
2            Entire condominium
3              Entire apartment
4     Entire serviced apartment
...                         ...
5515           Entire apartment
5516               Private room
5517           Entire apartment
5518           Entire apartment
5519           Entire apartment

[5520 rows x 1 columns]

In [19]:
from sklearn.feature_extraction import DictVectorizer

vec = DictVectorizer(sparse=False, dtype=int)

# get list of dicts from `type` column
data = [{'type':v} for v in df.type]

t = vec.fit_transform(data)
names = vec.feature_names_

pd.DataFrame(t, columns=names)

      type=Cycladic house  type=Earth house  ...  type=Shared room  type=Tiny house
0                       0                 0  ...                 0                0
1                       0                 0  ...                 0                0
2                       0                 0  ...                 0                0
3                       0                 0  ...                 0                0
4                       0                 0  ...                 0                0
...                   ...               ...  ...               ...              ...
5515                    0                 0  ...                 0                0
5516                    0                 0  ...                 0                0
5517                    0                 0  ...                 0                0
5518                    0                 0  ...                 0                0
5519                    0                 0  ...                 0                0

[5520 rows x 21 columns]

pd.get_dummies(df['type'])

In [23]:

pd.get_dummies(df['type']).head(), df['type'].head()

(   Cycladic house  Earth house  Entire apartment  ...  Room  Shared room  Tiny house
 0               0            0                 0  ...     0            0           0
 1               0            0                 1  ...     0            0           0
 2               0            0                 0  ...     0            0           0
 3               0            0                 1  ...     0            0           0
 4               0            0                 0  ...     0            0           0

 [5 rows x 21 columns], 0                  Entire loft
 1             Entire apartment
 2           Entire condominium
 3             Entire apartment
 4    Entire serviced apartment
 Name: type, dtype: object)

In [24]:
df.title

0             Jeddah 28th Red sea view  DAMAC Al Jawharah
1              Apartment with fantastic sea and city view
2       High-rise Luxury Apartment With Stunning City ...
3                   Stylish apartment in a great location
4           Luxury VIP SUITE Apartment (Private Building)
                              ...
5515                        Mabaat Homes, Diyar Alsalamah
5516                 Two Bedroom Apartment شقة غرفتين نوم
5517             "Cozy  apartment, Best choice in Jeddah"
5518             Furnished Apartment شقة مفروشةشارع فسطين
5519           Bed room with living room affordable price
Name: title, Length: 5520, dtype: object

In [26]:
from sklearn.feature_extraction.text import CountVectorizer
vec = CountVectorizer()
X = vec.fit_transform(df.title)

pd.DataFrame(X.toarray(), columns=vec.get_feature_names())

      107  108  112  17  17th  ...  𝙉𝙚𝙬  𝙖𝙥𝙖𝙧𝙩𝙢𝙚𝙣𝙩  𝙞𝙣  𝙣𝙚𝙞𝙜𝙝𝙗𝙤𝙧𝙝𝙤𝙤𝙙  𝙦𝙪𝙞𝙚𝙩
0       0    0    0   0     0  ...    0          0   0             0      0
1       0    0    0   0     0  ...    0          0   0             0      0
2       0    0    0   0     0  ...    0          0   0             0      0
3       0    0    0   0     0  ...    0          0   0             0      0
4       0    0    0   0     0  ...    0          0   0             0      0
...   ...  ...  ...  ..   ...  ...  ...        ...  ..           ...    ...
5515    0    0    0   0     0  ...    0          0   0             0      0
5516    0    0    0   0     0  ...    0          0   0             0      0
5517    0    0    0   0     0  ...    0          0   0             0      0
5518    0    0    0   0     0  ...    0          0   0             0      0
5519    0    0    0   0     0  ...    0          0   0             0      0

[5520 rows x 752 columns]

In [51]:
tf = pd.DataFrame(X.toarray(), columns=vec.get_feature_names())
c = tf.drop(columns = ['و٣','ولمن', 'وقتا','وقت','يمتاز','𝙞𝙣'])

In [52]:
c

      107  108  112  17  17th  ...  ٤غرف  𝙉𝙚𝙬  𝙖𝙥𝙖𝙧𝙩𝙢𝙚𝙣𝙩  𝙣𝙚𝙞𝙜𝙝𝙗𝙤𝙧𝙝𝙤𝙤𝙙  𝙦𝙪𝙞𝙚𝙩
0       0    0    0   0     0  ...     0    0          0             0      0
1       0    0    0   0     0  ...     0    0          0             0      0
2       0    0    0   0     0  ...     0    0          0             0      0
3       0    0    0   0     0  ...     0    0          0             0      0
4       0    0    0   0     0  ...     0    0          0             0      0
...   ...  ...  ...  ..   ...  ...   ...  ...        ...           ...    ...
5515    0    0    0   0     0  ...     0    0          0             0      0
5516    0    0    0   0     0  ...     0    0          0             0      0
5517    0    0    0   0     0  ...     0    0          0             0      0
5518    0    0    0   0     0  ...     0    0          0             0      0
5519    0    0    0   0     0  ...     0    0          0             0      0

[5520 rows x 746 columns]

In [78]:
link2 = 'https://gist.githubusercontent.com/michhar/2dfd2de0d4f8727f873422c5d959fff5/raw/fa71405126017e6a37bea592440b4bee94bf7b9e/titanic.csv'
tt = pd.read_csv(link2)

tt['Age']

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ...
886    27.0
887    19.0
888     NaN
889    26.0
890    32.0
Name: Age, Length: 891, dtype: float64

In [60]:
tt.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [159]:
from sklearn.impute import SimpleImputer
import numpy as np 
r = tt[['Age']]

imp = SimpleImputer(missing_values=np.nan, strategy='mean')

X2 = imp.fit_transform(r)

x = pd.DataFrame(X2) 
big_df = pd.concat([tt,x], axis=1)

big_df = big_df.drop(columns="Age")
big_df = y.rename(columns={0:'Age'})
big_df


# pd.DataFrame(tt['Age']).fillna(0)

     PassengerId  Survived  Pclass  ... Cabin Embarked        Age
0              1         0       3  ...   NaN        S  22.000000
1              2         1       1  ...   C85        C  38.000000
2              3         1       3  ...   NaN        S  26.000000
3              4         1       1  ...  C123        S  35.000000
4              5         0       3  ...   NaN        S  35.000000
..           ...       ...     ...  ...   ...      ...        ...
886          887         0       2  ...   NaN        S  27.000000
887          888         1       1  ...   B42        S  19.000000
888          889         0       3  ...   NaN        S  29.699118
889          890         1       1  ...  C148        C  26.000000
890          891         0       3  ...   NaN        Q  32.000000

[891 rows x 12 columns]

In [160]:
# from sklearn.pipeline import FeatureUnion, make_pipeline
# imp = make_pipeline(SimpleImputer(missing_values=np.nan, strategy='mean'))
# X2 = imp.fit_transform(r)
# X2
# big_df = pd.concat([tt,X2], axis=1)

# big_df